- build.gradle.kts
> Update uk.gov.justice.hmpps.gradle-spring-boot reference

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/models/registration/HmppsDomainEventMessage.kt
> Hia 756 fix security pipeline

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/extensions/AuthorisationFilter.kt
> Replace . with - for subjectDistinguishedName for authorization

- build.gradle.kts
> Fix security pipeline

- docs/guides/setting-up-a-new-consumer.md
> Update setting up a new consumer doc

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/models/enums/IntegrationEventTypes.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/SubscriberService.kt
> PI-2370 - update client filter and small refactor to enum

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/exceptions/NotFoundException.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/listeners/HmppsDomainEventsListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/HmppsDomainEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/integration/listeners/HmppsDomainEventsListenerIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/listeners/HmppsDomainEventsListenerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/HmppsDomainEventServiceTest.kt
> PI-2405 Failed messages to dlq

- helm_deploy/hmpps-integration-events/values.yaml
- helm_deploy/values-dev.yaml
> PI-2405 - update helm files to configure sentry

- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
> PI-2405 - update helm files to configure sentry for preprod and prod

- docker-compose.yml
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/models/enums/IntegrationEventTypes.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/models/registration/HmppsDomainEventMessage.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/HmppsDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/SubscriberService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/integration/helpers/DomainEvents.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/listeners/HmppsDomainEventsListenerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/HmppsDomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/SubscriberServiceTests.kt
> Pi 2364 notification channel persons hmpps

- Dockerfile
File is still referenced after being removed in previous PR
Remove the reference
> PI-2404 Remove unused file from Dockerfile

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/models/enums/IntegrationEventTypes.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/models/registration/HmppsDomainEventMessage.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/HmppsDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/SubscriberService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/listeners/HmppsDomainEventsListenerLicenceConditionTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/HmppsDomainEventServiceLicenceConditionTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/HmppsDomainEventServiceTest.kt
> PI-2372 - add new notification event

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/models/enums/IntegrationEventTypes.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/models/registration/HmppsDomainEventMessage.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/HmppsDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/SubscriberService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/integration/helpers/DomainEvents.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/listeners/HmppsDomainEventsListenerLicenceConditionTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/listeners/HmppsDomainEventsListenerROSHTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/HmppsDomainEventServiceLicenceConditionTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/HmppsDomainEventServiceROSHTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/HmppsDomainEventServiceTest.kt
> Pi 2369 notification channel persons hmpps id risks serious harm

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/EventNotifierService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/IntegrationEventTopicService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/EventNotifierServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/IntegrationEventTopicServiceTests.kt
> Pi 2444 do not hide exception

- .github/dependabot.yml
- .github/workflows/dependabot.yml
We have outdated dependencies
Enable Dependabot (with auto-merging of minor changes), to improve management of dependency upgrades.
> PI-2496 Enable Dependabot

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/models/enums/IntegrationEventTypes.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/SubscriberService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/listeners/HmppsDomainEventsListenerPLPReviewUpdatedTest.kt
> added handling of review schedule events

- helm_deploy/hmpps-integration-events/values.yaml
- src/main/resources/application-dev.yml
> refresh filter

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/models/enums/IntegrationEventTypes.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/SubscriberService.kt
> corrected plp path

- .gitignore
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/models/enums/IntegrationEventTypes.kt
> changed the default URL in the induction messages to be the history one

- .circleci/config.yml
- helm_deploy/values-preprod.yaml
> enable events service in pre prod

- helm_deploy/values-preprod.yaml
> update preprod helm file

- helm_deploy/hmpps-integration-events/values.yaml
- helm_deploy/values-dev.yaml
> moved config not used in prod into dev

- helm_deploy/hmpps-integration-events/values.yaml
- helm_deploy/values-dev.yaml
> reverted moved config not used in prod into dev

- .circleci/config.yml
- helm_deploy/hmpps-integration-events/values.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
> updating config

- helm_deploy/values-preprod.yaml
- src/main/resources/application-preprod.yml
> adding preprod config

- .circleci/config.yml
- helm_deploy/values-prod.yaml
- src/main/resources/db/migration/application-prod.yml
> final config to deploy to prod

- docs/guides/updating-certificates.md
Document the required steps to update the certificates that we use to get config from Integration API
> Document steps required to refresh event service certificates.

- docs/guides/setting-up-a-new-consumer.md
- docs/guides/updating-certificates.md
- helm_deploy/hmpps-integration-events/values.yaml
- src/main/resources/application-dev.yml
Add bmadley event queue to list of subscribers to allow us to test changes to event system.
Add more detail to documentation of setting up a new queue.
> Add bmadley event queue to list of subscribers

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/listeners/HmppsDomainEventsListener.kt
`hmppsDomainEventType` is actually an IntegrationEvent
> Rename confusing variable.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/models/enums/IntegrationEventType.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/integration/listeners/HmppsDomainEventsListenerIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/listeners/PersonEventTest.kt
-Add new person events to relevant integration event types
-Add new person events to 8 new endpoints and update associated tests
> HMAI-575 Add new person events to relevant integration event types

- README.md
Aiming to add a bit of clarity about how the Integration Events system works, as we've found quite a few misconceptions about what it does and it's not exactly intuitive.
> Hmai 593 document the 3 integration events processes

- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/HmppsDomainEventServiceTest.kt
* Current tests use parameterized tests to cover multiple domain events in a single method, which reduces test clarity and makes individual event coverage less explicit.
* Team decision is to prioritize clarity and maintainability by having dedicated unit and integration tests for each domain event.
* Refactored unit test class: replaced all parameterized tests with individual `@Test` methods, each covering a single domain event scenario.
> HMAI-581 Refactoring tests on events repo

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/DeleteProcessedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationevents/services/StateEventNotifierService.kt
Added logging to StateEventNotifierService and DeleteService
> HIA-930: Added logging to scheduled tasks
